-- Dados de exemplo — três categorias e dois artigos, em português de Portugal,
-- para veres a revista com conteúdo real antes de escreveres o teu.
-- Corre depois das migrações (0001 e 0002).

insert into public.categorias (nome, slug, descricao, ordem) values
  ('Limites', 'limites', 'Sobre dizer não, proteger o teu tempo e deixar de pedir desculpa por existir.', 1),
  ('Relações', 'relacoes', 'O que sustenta uma relação depois da paixão inicial passar.', 2),
  ('Autoestima', 'autoestima', 'A distância entre quem somos e quem dizemos ser — e como a encurtar.', 3)
on conflict (slug) do nothing;

insert into public.artigos (
  slug, titulo, subtitulo, resumo, conteudo, conteudo_html,
  categoria_id, estado, publicado_em, tempo_leitura, seo_titulo, seo_descricao
)
select
  'o-nao-que-nunca-disseste',
  'O não que nunca disseste',
  'Porque é que dizer que sim a tudo tem um preço que só se vê mais tarde',
  'Cada sim que devia ter sido não fica algures no corpo. Um dia a conta chega. Sobre limites, cansaço e a coragem de decepcionar alguém para não te traíres a ti.',
  $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Houve um dia em que disseste que sim e o corpo disse que não. Foi antes de saberes nomear a diferença."}]},{"type":"paragraph","content":[{"type":"text","text":"Cresceste a aprender que amar é ceder. Que um bom filho, um bom amigo, um bom parceiro, é aquele que nunca é peso para ninguém. Por isso aprendeste a engolir o teu próprio peso, dia após dia, até deixares de o sentir como peso — passou a ser só o teu jeito de estar no mundo."}]},{"type":"paragraph","content":[{"type":"text","text":"Ninguém te disse que essa conta chega sempre. Em cansaço, em ressentimento sem nome, num corpo que dói sem razão médica. Chega disfarçada de mau feitio, de \"hoje não estou capaz\", de uma vontade estranha de desaparecer por umas horas."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"O limite não é uma parede"}]},{"type":"paragraph","content":[{"type":"text","text":"Um limite não existe para afastar as pessoas. Existe para que continues a existir depois de estares com elas. É a diferença entre uma relação que te esvazia e uma que te devolve alguma coisa — mesmo quando essa alguma coisa é só o teu próprio espaço de volta."}]},{"type":"paragraph","content":[{"type":"text","text":"Dizer não a um pedido não é dizer não à pessoa. É raro que alguém entenda isto da primeira vez que o fazes, porque também tu não entendias. Vais ser mal interpretado. Vais sentir a tentação de explicar de mais, de te justificares como se um limite precisasse de um julgamento a validá-lo."}]},{"type":"blockquote","content":[{"type":"paragraph","content":[{"type":"text","text":"Não precisas de merecer o teu próprio limite. Precisas só de o dizer."}]}]},{"type":"paragraph","content":[{"type":"text","text":"A primeira vez dói mais do que devia. A segunda, um pouco menos. Não porque as pessoas à tua volta mudem depressa — porque tu começas a acreditar que tens esse direito, e é essa crença, não a reação delas, que te sustenta."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"O que fica por dizer"}]},{"type":"paragraph","content":[{"type":"text","text":"Pensa nos últimos meses. Quantos nãos ficaram por dizer? Quantos sins saíram só porque dizer não parecia mais complicado do que aguentar? Não é preciso resposta em voz alta — é só para saberes que há aí um número, e que ele tem peso."}]},{"type":"paragraph","content":[{"type":"text","text":"O trabalho não é tornares-te alguém que diz não a tudo. É tornares-te alguém que sabe, antes de abrir a boca, o que está realmente a escolher. Essa escolha, feita com consciência, é o oposto do egoísmo que temes ser. É o começo de uma relação verdadeira contigo — e só depois, com os outros."}]}]}$j$,
  '<p>Houve um dia em que disseste que sim e o corpo disse que não. Foi antes de saberes nomear a diferença.</p><p>Cresceste a aprender que amar é ceder. Que um bom filho, um bom amigo, um bom parceiro, é aquele que nunca é peso para ninguém. Por isso aprendeste a engolir o teu próprio peso, dia após dia, até deixares de o sentir como peso — passou a ser só o teu jeito de estar no mundo.</p><p>Ninguém te disse que essa conta chega sempre. Em cansaço, em ressentimento sem nome, num corpo que dói sem razão médica. Chega disfarçada de mau feitio, de "hoje não estou capaz", de uma vontade estranha de desaparecer por umas horas.</p><h2>O limite não é uma parede</h2><p>Um limite não existe para afastar as pessoas. Existe para que continues a existir depois de estares com elas. É a diferença entre uma relação que te esvazia e uma que te devolve alguma coisa — mesmo quando essa alguma coisa é só o teu próprio espaço de volta.</p><p>Dizer não a um pedido não é dizer não à pessoa. É raro que alguém entenda isto da primeira vez que o fazes, porque também tu não entendias. Vais ser mal interpretado. Vais sentir a tentação de explicar de mais, de te justificares como se um limite precisasse de um julgamento a validá-lo.</p><blockquote><p>Não precisas de merecer o teu próprio limite. Precisas só de o dizer.</p></blockquote><p>A primeira vez dói mais do que devia. A segunda, um pouco menos. Não porque as pessoas à tua volta mudem depressa — porque tu começas a acreditar que tens esse direito, e é essa crença, não a reação delas, que te sustenta.</p><h2>O que fica por dizer</h2><p>Pensa nos últimos meses. Quantos nãos ficaram por dizer? Quantos sins saíram só porque dizer não parecia mais complicado do que aguentar? Não é preciso resposta em voz alta — é só para saberes que há aí um número, e que ele tem peso.</p><p>O trabalho não é tornares-te alguém que diz não a tudo. É tornares-te alguém que sabe, antes de abrir a boca, o que está realmente a escolher. Essa escolha, feita com consciência, é o oposto do egoísmo que temes ser. É o começo de uma relação verdadeira contigo — e só depois, com os outros.</p>',
  c.id, 'publicado', now() - interval '3 days', 4,
  'O não que nunca disseste — Pedro Correia de Oliveira',
  'Sobre limites, cansaço e a coragem de decepcionar alguém para não te traíres a ti.'
from public.categorias c where c.slug = 'limites'
on conflict (slug) do nothing;

insert into public.artigos (
  slug, titulo, subtitulo, resumo, conteudo, conteudo_html,
  categoria_id, estado, publicado_em, tempo_leitura, seo_titulo, seo_descricao
)
select
  'quem-dizemos-ser',
  'Quem dizemos ser',
  'A distância entre a pessoa que mostras e a pessoa que és quando ninguém vê',
  'Há uma versão tua que publicas e uma versão tua que vives. Sobre a distância entre as duas, e porque fechá-la é o único caminho para deixar de estar cansado de ti próprio.',
  $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Há uma versão tua que mostras e uma versão tua que sobra depois de a porta se fechar. Entre as duas vive uma distância que ninguém te ensinou a medir."}]},{"type":"paragraph","content":[{"type":"text","text":"Não é hipocrisia — quase ninguém escolhe isto de propósito. É sobrevivência aprendida cedo: mostra o que é aceite, esconde o que não é. Com o tempo, deixa de ser uma escolha e passa a ser um hábito do corpo inteiro."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"O cansaço que não tem nome"}]},{"type":"paragraph","content":[{"type":"text","text":"Manter duas versões de ti próprio custa energia todos os dias, mesmo quando não reparas. É esse o cansaço estranho que aparece sem esforço físico que o justifique — o corpo a pagar a conta de uma actuação que nunca pediste para fazer, mas que também nunca decidiste parar."}]},{"type":"paragraph","content":[{"type":"text","text":"A pergunta não é \"como deixo de mostrar uma versão melhorada de mim\". Isso, até certo ponto, é normal e humano. A pergunta é outra: até que distância consegues viver sem deixares de te reconhecer?"}]},{"type":"blockquote","content":[{"type":"paragraph","content":[{"type":"text","text":"Não é preciso mostrar tudo. É preciso que o que mostras não seja mentira sobre o que és."}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Fechar a distância, não a exposição"}]},{"type":"paragraph","content":[{"type":"text","text":"Fechar essa distância não significa expor-te por inteiro a toda a gente. Significa que a pessoa que apareces a ser, mesmo que seja só uma parte de ti, seja verdadeira nessa parte. Não uma personagem construída para agradar — uma amostra honesta do todo."}]},{"type":"paragraph","content":[{"type":"text","text":"Começa pequeno. Uma conversa onde dizes o que sentes em vez do que seria mais fácil de ouvir. Um dia em que não escondes o cansaço atrás de um \"estou bem\". Cada vez que a versão pública e a versão privada se aproximam um pouco, o cansaço estranho perde um pouco de força."}]},{"type":"paragraph","content":[{"type":"text","text":"Não é sobre a imagem que os outros têm de ti. É sobre deixares de precisar de duas pessoas para viver um só dia."}]}]}$j$,
  '<p>Há uma versão tua que mostras e uma versão tua que sobra depois de a porta se fechar. Entre as duas vive uma distância que ninguém te ensinou a medir.</p><p>Não é hipocrisia — quase ninguém escolhe isto de propósito. É sobrevivência aprendida cedo: mostra o que é aceite, esconde o que não é. Com o tempo, deixa de ser uma escolha e passa a ser um hábito do corpo inteiro.</p><h2>O cansaço que não tem nome</h2><p>Manter duas versões de ti próprio custa energia todos os dias, mesmo quando não reparas. É esse o cansaço estranho que aparece sem esforço físico que o justifique — o corpo a pagar a conta de uma actuação que nunca pediste para fazer, mas que também nunca decidiste parar.</p><p>A pergunta não é "como deixo de mostrar uma versão melhorada de mim". Isso, até certo ponto, é normal e humano. A pergunta é outra: até que distância consegues viver sem deixares de te reconhecer?</p><blockquote><p>Não é preciso mostrar tudo. É preciso que o que mostras não seja mentira sobre o que és.</p></blockquote><h2>Fechar a distância, não a exposição</h2><p>Fechar essa distância não significa expor-te por inteiro a toda a gente. Significa que a pessoa que apareces a ser, mesmo que seja só uma parte de ti, seja verdadeira nessa parte. Não uma personagem construída para agradar — uma amostra honesta do todo.</p><p>Começa pequeno. Uma conversa onde dizes o que sentes em vez do que seria mais fácil de ouvir. Um dia em que não escondes o cansaço atrás de um "estou bem". Cada vez que a versão pública e a versão privada se aproximam um pouco, o cansaço estranho perde um pouco de força.</p><p>Não é sobre a imagem que os outros têm de ti. É sobre deixares de precisar de duas pessoas para viver um só dia.</p>',
  c.id, 'publicado', now() - interval '1 day', 3,
  'Quem dizemos ser — Pedro Correia de Oliveira',
  'A distância entre a pessoa que mostras e a pessoa que és quando ninguém vê, e porque fechá-la é o caminho para deixares de estar cansado de ti próprio.'
from public.categorias c where c.slug = 'autoestima'
on conflict (slug) do nothing;
